import './globals.css'
import Navbar from '@/components/Navbar/Navbar'
import Modal from '@/components/Modal/Modal'
import SocialIcons from '@/components/socialIcons/SocialIcons';
import Footer from '@/components/Footer/Footer';
import { Josefin_Sans } from 'next/font/google'
import { CartProvider } from '@/CartContext';

const josefin = Josefin_Sans({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700']
})

export const metadata = {
  title: 'Life Etc.',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={`${josefin.className}`}>
        <CartProvider> 
          <div className='container'>
            <Navbar />
            {children}
          </div>
          <Modal />
          <SocialIcons />
          <Footer />
        </CartProvider>
      </body>
    </html>
  )
}